name: Nelson tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    docker:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build image
              run: docker-compose build php

            - name: test directories
              run: mkdir vendor && chmod -R 0777 vendor

            - name: Install dependencies
              run: docker-compose run --rm php composer install

            - name: Code style check
              run: docker-compose run --rm php vendor/bin/php-cs-fixer fix --dry-run -v --diff --config=.php_cs.php

            - name: Static checks
              run: docker-compose run --rm php vendor/bin/phpstan analyze src --level 5

            - name: Run specs
              run: docker-compose run --rm php vendor/bin/phpspec run

    php:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.1', '8.2']
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Install dependencies
              run: composer update

            - name: Run specs
              run: vendor/bin/phpspec run
